### ISSUE TITLE
inline-react-svg not working on icons properly?

### ISSUE THREAD

**Issue by llamerr** [dwarvesf/nextjs-boilerplate#14]
### Describe the bug

> How does the program work in its current state? A clear and concise description of what you expected to happen.

After installing an app and going to Dahsboard with demo account, I see lots of errors similar to this one:

> Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

### Steps to reproduce

Install and start app with:

> git clone --depth=1 git@github.com:dwarvesf/nextjs-boilerplate.git my-project-name
> cd my-project-name
> yarn install
> yarn dev

Open http://localhost:3000/ and login with demo account

### Expected behaviour

Errors should not be present, `fillRule` should be generated instead of `fill-rule`.

### Environment

You may write here the specifications like the version of the project, operating system, or hardware if applicable.

**Desktop (please complete the following information):**
 - MacOS 12.5.1
 - Chrome

I tried to debug it and inside that plugin found transformSvg which does that

> // converts
> // `<svg stroke-width="5">`
> // to
> // `<svg strokeWidth="5">`
> // don't convert any custom data-* or aria-* attributes just wrap in quotes

but it's not triggered
Looking further I found this condition, that supposedly executes that transform: 

> node.callee.name === 'require'

I still debugging it, but seems it only works on svg import, and not by passing content with:

> babel.transform(content

Maybe something had changed, or was this error present before?

**Comment by zlatanpham** [comment]
Hi @llamerr, thanks for reporting this issue. This is a known problem; the attributes to be converted in camelCase aren't properly identified by [the transformation pipeline](https://github.com/dwarvesf/nextjs-boilerplate/blob/master/scripts/utils.js#L18). We'll take a look at fixing this soon, but if you'd like to contribute, please feel free to fix it yourself and send us a pull request.

**Comment by tuanddd** [comment]
Hey @llamerr I've submitted a PR to resolve this, hopefully it'll be merged soon.

**Comment by tuanddd** [comment]
Great news @llamerr it's been merged! Can you try again on your end?

**Comment by llamerr** [comment]
@tuanddd Just checked, everything works great. Thank you for a quick fix!
